config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  resources :artists do
    resources :albums
  end

  resources :albums do
    resources :songs
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_artist
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = @artist.albums
  end

  def show
  end

  def new
    @album = @artist.albums.new
  end

  def edit
  end

  def create
    @album = @artist.albums.new(album_params)

    if @album.save
      redirect_to [@artist, @album]
    else
      render :new
    end
  end

  def update
    if @album.update(album_params)
      redirect_to [@artist, @album]
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to artist_albums_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:name, :genre, :year)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)
    
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:first_name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @album.songs
  end

  def show
  end

  def new
    @song = @album.songs.new
  end

  def edit
  end

  def create
    @song = @album.songs.new(song_params)

    if @song.save
      redirect_to [@album, @song]
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to [@album, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to album_songs_path
  end

  private    
  def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :genre, :play_count)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
<h1><%= @album.id ? 'Edit Album' : 'Create Album' %></h1>
<hr />
<%= form_with(model: [@artist, @album], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <%= f.label :year %>
  <%= f.text_field :year, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", artist: @artist, album: @album %>

<%= link_to "Back", artist_albums_path(@artist) %> |
<%= link_to 'Add Song', new_album_song_path(@album) %> |
<%= link_to 'Back To Albums', artist_albums_path(@artist) %>

app/views/albums/index.html.erb
<h1>Click an Album To View It</h1>
<br />

<ul>
  <% @albums.each do |album| %>
    <li><%= link_to album.name, [@artist, album] %></li> 
  <% end %>
</ul>

<br />
<%= link_to 'Add Album', new_artist_album_path(@artist) %> |
<%= link_to 'Back To Artist', artist_path(@artist) %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "form", artist: @artist, album: @album %>

<%= link_to "Back", artist_albums_path(@artist) %>

app/views/albums/show.html.erb
<h1><%= @artist.group %></h1>
<h4>Name: <%= @album.name %></h4>
<h4>Species: <%= @album.genre %></h4>
<h4>Age: <%= @album.year %></h4>
<br />
<%= link_to 'Edit Album', edit_artist_album_path([@artist, @album]) %> |
<%= link_to 'Delete Album', [@artist, @album], method: :delete %> |
<%= link_to 'View Songs', album_songs_path(@album) %> |
<%= link_to 'Back To Albums', artist_albums_path(@artist) %>

app/views/artists/_form.html.erb
<%= form_with(model: @artist, local: true, class: "ui form") do |f| %>
  <div class="field">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true, autofocus: true %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true%>

  <%= f.label :group %>
  <%= f.text_field :group, required: true%>

  <%= f.label :genre %>
  <%= f.text_field :genre, required: true%>

  <%= f.label :age %>
  <%= f.text_field :age, required: true%>

  <%= f.label :avatar %>
  <%= f.text_field :avatar, required: true%>
  
  <%= f.submit nil, class: "ui button"%>

<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", artist: @artist %>

<%= link_to "Show", artist_path(@artist) %> |
<%= link_to 'Add Album', new_artist_album_path(@artist) %> |
<%= link_to "Back", artists_path %>

app/views/artists/index.html.erb
<h1 class="ui header">All Artist</h1>
<%= link_to 'New Artist', new_artist_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @artists.each do |artist| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= artist.avatar %>?set=set2" />
        </div>
        <div class="content">
          <%= link_to "#{artist.first_name} #{artist.last_name}", artist, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="ui basic green button">
              <%= link_to 'Edit', edit_artist_path(artist) %>
            </div>
            <div class="ui basic red button">
              <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<h1>New ARTIST</h1>

<%= render "form", person: @artist %>

<%= link_to "Back", artists_path %>

app/views/artists/show.html.erb
<div class="ui card">
  <div class="image">
    <img src="https://robohash.org/<%= @artist.avatar %>?set=set2" />
  </div>
  <div class="content">
    <p class="header">
      <%= @artist.first_name %> <%= @artist.last_name %>
    </p>
    <div class="meta">
      <span><%= @artist.group %></span>
    </div>
    <div class="description">
      <%= @artist.genre %>
    </div>
    <div class="description">
      <%= @artist.age %>
    </div>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_artist_path(@artist) %> |
    <%= link_to 'View Albums', artist_albums_path(@artist) %> |
    <%= link_to 'All Artist', artists_path %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'Artists', artists_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
    <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_with(model: [@album, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <%= f.label :play_count %>
  <%= f.text_field :play_count, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form", album: @album, song: @song %>

<%= link_to "Back", album_songs_path(@album) %>

app/views/songs/index.html.erb
<h1>Click a Song To View It</h1>
<%= link_to 'Add Song', new_album_song_path(@album) %>
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.title, [@album, song] %></li> 
  <% end %>
</ul>

<br />
<%= link_to 'Add Song', new_album_song_path(@album) %> |

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form", album: @album, song: @song %>

<%= link_to "Back", album_songs_path(@album) %>

app/views/songs/show.html.erb
<h1><%= @album.name %></h1>
<h4>Name: <%= @song.title %></h4>
<h4>Species: <%= @song.genre %></h4>
<h4>Age: <%= @song.play_count %></h4>
<br />
<%= link_to 'Edit Song', edit_album_song_path([@album, @song]) %> |
<%= link_to 'Delete Song', [@album, @song], method: :delete %> |
<%= link_to 'Back To Songs', album_songs_path(@album) %>